import AppKit
import Foundation
import Observation
import SwiftData

// MARK: - ClipboardService
//
// Surveille le presse-papiers et enregistre chaque nouvelle copie.
//
// Methode : sondage de `NSPasteboard.general.changeCount`. macOS n'expose
// aucune notification de changement du presse-papiers ; le sondage est la seule
// approche publique, et c'est celle qu'emploient tous les gestionnaires de
// l'App Store. Le compteur est un entier — le lire ne deserialise rien, et le
// contenu n'est lu que lorsqu'il a effectivement change.
//
// Vie privee : les contenus marques comme confidentiels ou transitoires sont
// ignores (voir `isConcealed`). C'est la convention respectee par les
// gestionnaires de mots de passe ; sans elle, un mot de passe copie
// atterrirait dans l'historique.

@MainActor
@Observable
final class ClipboardService {

    /// Intervalle de sondage. 500 ms : sous ce seuil on brule du CPU pour rien,
    /// au-dessus une copie suivie d'une seconde copie rapide serait manquee.
    private let interval: Duration = .milliseconds(500)

    private let pasteboard: NSPasteboard
    private let context: ModelContext
    private var lastChangeCount: Int
    private var pollTask: Task<Void, Never>?

    /// Nombre maximal d'entrees conservees. Au-dela, les plus anciennes non
    /// favorites sont supprimees.
    var historyLimit: Int

    init(
        pasteboard: NSPasteboard = .general,
        context: ModelContext,
        historyLimit: Int = 200
    ) {
        self.pasteboard = pasteboard
        self.context = context
        self.historyLimit = historyLimit
        self.lastChangeCount = pasteboard.changeCount
    }

    // MARK: Cycle de vie

    func start() {
        guard pollTask == nil else { return }
        pollTask = Task { [weak self] in
            while !Task.isCancelled {
                self?.pollOnce()
                guard let interval = self?.interval else { return }
                try? await Task.sleep(for: interval)
            }
        }
    }

    func stop() {
        pollTask?.cancel()
        pollTask = nil
    }

    // MARK: Sondage

    private func pollOnce() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current
        guard !isConcealed else { return }
        capture()
    }

    /// Marqueurs conventionnels (nspasteboard.org) posés par les gestionnaires
    /// de mots de passe et les utilitaires de copie temporaire. Les respecter
    /// evite d'archiver un secret, et c'est un point que la revue App Store
    /// verifie sur ce type d'app.
    private var isConcealed: Bool {
        let markers: Set<String> = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType"
        ]
        let present = pasteboard.types?.map(\.rawValue) ?? []
        return present.contains { markers.contains($0) }
    }

    // MARK: Capture

    private func capture() {
        guard let entry = makeEntry() else { return }

        // Une meme valeur recopiee remonte en tete au lieu de creer un doublon.
        if let existing = findEntry(matching: entry.fingerprint) {
            existing.createdAt = .now
            try? context.save()
            return
        }

        context.insert(entry)
        trimHistory()
        try? context.save()
    }

    private func makeEntry() -> ClipboardEntry? {
        let source = NSWorkspace.shared.frontmostApplication
        let bundleID = source?.bundleIdentifier
        let iconData = source?.icon?.pngData(size: NSSize(width: 32, height: 32))

        // Ordre de detection : du plus specifique au plus general. Un fichier
        // depose porte aussi une representation texte ; tester l'URL d'abord
        // evite de l'enregistrer comme un chemin en clair.
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL],
           let url = urls.first, url.isFileURL {
            return ClipboardEntry(
                kind: .file,
                text: url.path,
                sourceBundleID: bundleID,
                sourceIconData: iconData
            )
        }

        if let image = NSImage(pasteboard: pasteboard),
           let data = image.pngData(size: NSSize(width: 320, height: 320)) {
            return ClipboardEntry(
                kind: .image,
                imageData: data,
                sourceBundleID: bundleID,
                sourceIconData: iconData
            )
        }

        guard let string = pasteboard.string(forType: .string),
              !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else { return nil }

        let kind: ClipboardKind = NSColor(hex: string) != nil ? .color : .text
        return ClipboardEntry(
            kind: kind,
            text: string,
            sourceBundleID: bundleID,
            sourceIconData: iconData
        )
    }

    // MARK: Entretien

    private func findEntry(matching fingerprint: String) -> ClipboardEntry? {
        let descriptor = FetchDescriptor<ClipboardEntry>(
            sortBy: [SortDescriptor(\.createdAt, order: .reverse)]
        )
        return (try? context.fetch(descriptor))?.first { $0.fingerprint == fingerprint }
    }

    /// Les favoris ne comptent pas dans la limite : les epingler signifie
    /// justement les soustraire a la purge automatique.
    private func trimHistory() {
        var descriptor = FetchDescriptor<ClipboardEntry>(
            predicate: #Predicate { !$0.isFavorite },
            sortBy: [SortDescriptor(\.createdAt, order: .reverse)]
        )
        descriptor.fetchLimit = 1000
        guard let entries = try? context.fetch(descriptor), entries.count > historyLimit else {
            return
        }
        for entry in entries.dropFirst(historyLimit) {
            context.delete(entry)
        }
    }
}

// MARK: - Rendu PNG
extension NSImage {
    /// Reduit l'image et l'encode en PNG. Stocker le TIFF d'origine ferait
    /// grossir la base d'un ordre de grandeur pour une vignette de 150 pt.
    func pngData(size target: NSSize) -> Data? {
        let ratio = min(target.width / max(size.width, 1), target.height / max(size.height, 1), 1)
        let scaled = NSSize(width: size.width * ratio, height: size.height * ratio)

        guard scaled.width >= 1, scaled.height >= 1 else { return nil }
        let output = NSImage(size: scaled)
        output.lockFocus()
        draw(in: NSRect(origin: .zero, size: scaled))
        output.unlockFocus()

        guard let tiff = output.tiffRepresentation,
              let bitmap = NSBitmapImageRep(data: tiff) else { return nil }
        return bitmap.representation(using: .png, properties: [:])
    }
}
